### ISSUE TITLE
Defining a schema-less endpoint

### ISSUE THREAD

**Issue by bomb-on** [RedTurtle/eve-sqlalchemy#134]
As per #118 (and also the linked comment in there [#900](https://github.com/nicolaiarocci/eve/issues/900#issuecomment-241341860)) it seems that it is not possible to define an "arbitrary" endpoint which is not interconnected with SQLAlchemy classes?

My intention is to have an app-wide authentication class, but have 1 endpoint completely open for public. I tried to achieve it like this:
```
DOMAIN = {
    'users': Users._eve_schema['users'],
    'data': Data._eve_schema['data'],
    'public': {'authentication': None}
}

# authentication class is defined on application level
application = Eve(auth=HMACAuth, settings=SETTINGS, data=SQL, validator=ValidatorSQL)
```
but I got `KeyError` when visiting `/public` URL.

So, my question...
Is it possible to define an endpoint which doesn't expect having any schema defined, or (for my specific use case) is it possible to define an endpoint which would ignore authentication in some other way?

Full stack trace:
```
2017-02-01 12:42:42 [e560c16579e241058440948a0a3bb56a] [127.0.0.1] DEBUG: [GET] /v1/public
2017-02-01 12:42:46 [e560c16579e241058440948a0a3bb56a] [127.0.0.1] ERROR: 'public'
Traceback (most recent call last):
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve/endpoints.py", line 52, in collections_endpoint
    response = get(resource, lookup)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve/methods/common.py", line 239, in rate_limited
    return f(*args, **kwargs)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve/auth.py", line 68, in decorated
    return f(*args, **kwargs)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve/methods/common.py", line 820, in decorated
    r = f(resource, **combined_args)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve/methods/get.py", line 99, in get
    cursor = app.data.find(resource, req, lookup)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve_sqlalchemy/__init__.py", line 116, in find
    args['sort'], client_embedded)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve_sqlalchemy/__init__.py", line 287, in _datasource_ex
    client_sort)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve/io/base.py", line 373, in _datasource_ex
    datasource, filter_, projection_, sort_ = self._datasource(resource)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve_sqlalchemy/__init__.py", line 281, in _datasource
    return self.datasource(resource)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve_sqlalchemy/__init__.py", line 269, in datasource
    model = self._model(resource)
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve_sqlalchemy/__init__.py", line 247, in _model
    return self.lookup_model(self._source(resource))
  File "/Users/oxxo/.pyenv/versions/io/lib/python3.4/site-packages/eve_sqlalchemy/__init__.py", line 60, in lookup_model
    return cls.driver.Model._decl_class_registry[model_name]
  File "/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4/weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: 'public'
```

**Comment by dkellner** [comment]
How do you plan to respond to requests to /public, i.e. where is the content coming from? If there still coming from the database, you can always use predefined filters (see http://python-eve.org/config.html#predefined-database-filters, or `eve_sqlalchemy/tests/test_settings.py`).

**Comment by bomb-on** [comment]
Hey! Sorry for late reply, I've been busy with some other projects...
Well, this might not be the requirement anymore, but the idea behind it was to have a non-secure endpoint which might serve any db-unrelated content. I was also in a situation that one endpoint was supposed to call a PostgreSQL stored procedure, meaning that there is no table structure per se...
